class StripePayGenerator < Rails::Generators::Base
  source_root File.expand_path('templates', __dir__)

  desc "Generate fake payment integration with polymorphic Payment model (no real payment gateway)"

  class_option :auth, type: :boolean, default: false,
               desc: "Add user association to payments (requires User model)"

  def check_user_model
    return unless options[:auth]

    unless File.exist?("app/models/user.rb")
      say "Error: User model not found.", :red
      say "Please ensure app/models/user.rb exists before using --auth option.", :yellow
      say "You can generate it with: rails generate authentication", :blue
      exit(1)
    end
  end

  def generate_migration
    if options[:auth]
      fields = "payable:references:index user:references amount:decimal currency:string status:string payment_method:string metadata:jsonb"
    else
      fields = "payable:references:index amount:decimal currency:string status:string payment_method:string customer_email:string metadata:jsonb"
    end

    # Use rails g model to auto-inject data_version field
    generate "model", "Payment #{fields}"

    # Post-process the generated migration to add polymorphic option and defaults
    migration_file = Dir.glob("db/migrate/*_create_payments.rb").last
    if migration_file
      content = File.read(migration_file)
      updated_content = content.gsub(
        /t\.references :payable/,
        't.references :payable, polymorphic: true, null: false'
      ).gsub(
        /t\.string :currency/,
        't.string :currency, default: "usd"'
      ).gsub(
        /t\.string :status/,
        't.string :status, default: "pending"'
      ).gsub(
        /add_index :payments, :payable/,
        '# Polymorphic index is automatically created by t.references'
      )
      File.write(migration_file, updated_content)
    end

    # Remove the auto-generated model file — we'll use our own template
    model_file = "app/models/payment.rb"
    File.delete(model_file) if File.exist?(model_file)

    # Remove auto-generated spec if exists
    spec_file = "spec/models/payment_spec.rb"
    File.delete(spec_file) if File.exist?(spec_file)
  end

  def generate_model
    @auth = options[:auth]
    template "payment.rb.erb", "app/models/payment.rb"
  end

  def add_user_association
    return unless options[:auth]

    user_model_path = "app/models/user.rb"
    return unless File.exist?(user_model_path)

    user_content = File.read(user_model_path)

    if user_content.include?("has_many :payments")
      say "User model already has has_many :payments, skipping...", :yellow
      return
    end

    if user_content.match(/has_many :sessions.*\n/)
      updated_content = user_content.sub(
        /(has_many :sessions.*\n)/,
        "\\1  has_many :payments, dependent: :destroy\n"
      )
      File.write(user_model_path, updated_content)
      say "Added has_many :payments to User model", :green
    else
      say "Warning: Could not find 'has_many :sessions' in User model", :yellow
      say "Please manually add 'has_many :payments' to your User model", :yellow
    end
  end

  def generate_controller
    @auth = options[:auth]
    template "payments_controller.rb.erb", "app/controllers/payments_controller.rb"
  end

  def generate_service
    @auth = options[:auth]
    template "fake_pay_service.rb.erb", "app/services/fake_pay_service.rb"
  end

  def generate_stimulus_controller
    template "javascript/payment_confirmation_controller.ts.erb",
             "app/javascript/controllers/payment_confirmation_controller.ts"
  end

  def add_routes
    route_content = <<~ROUTES
      resources :payments, only: [] do
        member do
          get :pay
          post :pay
          get :success
          get :failure
        end
      end
    ROUTES

    route route_content
  end

  def add_admin_routes
    route "resources :payments, only: [:index, :show]", namespace: :admin
  end

  def generate_admin_controller
    @auth = options[:auth]
    template "admin_payments_controller.rb.erb", "app/controllers/admin/payments_controller.rb"
  end

  def generate_admin_views
    @auth = options[:auth]
    template "admin_views/index.html.erb", "app/views/admin/payments/index.html.erb"
    template "admin_views/show.html.erb", "app/views/admin/payments/show.html.erb"
  end

  def generate_tests
    @auth = options[:auth]
    template "spec/requests/payment_integration_spec.rb.erb", "spec/requests/payment_integration_spec.rb"
  end

  def update_sidebar
    sidebar_path = "app/views/shared/admin/_sidebar.html.erb"
    if File.exist?(sidebar_path)
      sidebar_content = File.read(sidebar_path)

      generated_comment = "<!-- Generated by stripe_pay: payments -->"
      if sidebar_content.include?(generated_comment)
        say "Sidebar already contains payments menu item, skipping...", :yellow
        return
      end

      menu_item = <<~MENU_ITEM

        #{generated_comment}
        <li>
          <%= link_to admin_payments_path,
              class: "flex items-center px-4 py-2 text-sm text-foreground/70 hover:bg-primary/10 hover:text-primary rounded-lg transition-colors \#{'bg-primary/10 text-primary' if current_path.include?('/admin/payments')}" do %>
            <%= lucide_icon "credit-card", class: "w-5 h-5 mr-3" %>
            Payments
          <% end %>
        </li>
      MENU_ITEM

      updated_content = sidebar_content + menu_item
      File.write(sidebar_path, updated_content)
      say "Updated admin sidebar with Payments menu item", :green
    else
      say "Warning: Admin sidebar file not found. Please manually add menu item for Payments", :yellow
    end
  end

  def display_next_steps
    say "\n" + "="*70, :green
    say "Fake Payment Generator completed!", :green
    say "="*70, :green
    say "\nNext steps:", :yellow
    say "1. Setup: rails db:migrate", :cyan
    say "\n" + "="*70, :red
    say "⚠️  IMPORTANT: Complete these steps!", :red
    say "="*70, :red
    say "\nGenerated files:", :yellow
    say "  ✓ app/models/payment.rb - Payment model with polymorphic association", :green
    say "  ✓ app/controllers/payments_controller.rb - Fake pay controller", :green
    say "  ✓ app/services/fake_pay_service.rb - Simulated payment processing", :green
    say "  ✓ app/javascript/controllers/payment_confirmation_controller.ts - UI interaction", :green
    say "  ✓ spec/requests/payment_integration_spec.rb - Validates payable interface", :green
    say "\nYou MUST create:", :yellow
    say "  ✗ app/views/payments/pay.html.erb - Payment confirmation page", :red
    say "  ✗ app/views/payments/success.html.erb - Payment success page", :red
    say "  ✗ app/views/payments/failure.html.erb - Payment failure page (optional)", :red
    say "\n" + "="*70, :red
    say "⚠️  CRITICAL: Payment Flow Rules", :red
    say "="*70, :red
    say "\n1. Controller#create (in your business controller): Create order with status: 'pending'", :yellow
    say "   └─> Create payment record", :white
    say "   └─> Redirect to pay_payment_path(payment)", :white
    say "   └─> ❌ DO NOT add credits/items here!", :red
    say "\n2. User clicks pay on the confirmation page", :yellow
    say "\n3. PaymentsController#pay → FakePayService → process_payment_paid", :yellow
    say "   └─> Update order status to 'paid'", :white
    say "   └─> ✅ Add credits/items HERE (after payment confirmed)", :green
    say "\n" + "="*70, :yellow
    say "Payable Model Interface (implement in your business model):", :yellow
    say "="*70, :yellow
    say "\n  def customer_name    # → String: payer's name", :white
    say "  def customer_email   # → String: payer's email", :white
    say "  def payment_description # → String: what they're paying for", :white
    say "  def process_payment_paid # → called when payment succeeds", :white
    say "\n" + "="*70, :green
  end
end
