class ApplicationController < ActionController::Base
  # Authentication methods generated by authentication generator
  before_action :set_current_request_details
  before_action :restore_validator_context

  helper_method :current_user, :user_signed_in?, :current_validator_execution
  # Authentication public methods generated end

  # Allow browsers with broader compatibility
  allow_browser versions: {
    chrome: 80,
    firefox: 75,
    safari: 13,
    edge: 80,
    opera: 67
  }

  include FriendlyErrorHandlingConcern
  include DevelopmentCsrfBypassConcern
  include TurboCompatibleRenderConcern


  # Authentication private methods begin
  private

  def current_user
    Current.session&.user
  end

  def user_signed_in?
    current_user.present?
  end

  def authenticate_user!
    if session_record = find_session_record
      Current.session = session_record
    else
      redirect_to sign_in_path, alert: 'Please sign in to continue'
    end
  end

  alias_method :authenticate, :authenticate_user!

  def set_current_request_details
    Current.user_agent = request.user_agent
    Current.ip_address = request.ip

    if session_record = find_session_record
      Current.session = session_record
    else
      auto_login_default_user
    end
  end

  def auto_login_default_user
    default_email = 'demo@rlbox.ai'
    default_password = 'password123'

    user = User.find_by(email: default_email)
    unless user
      user = User.create!(
        email: default_email,
        password: default_password,
        password_confirmation: default_password,
        verified: true
      )
    end

    session_record = user.sessions.create!(
      user_agent: Current.user_agent,
      ip_address: Current.ip_address
    )

    cookies.signed.permanent[:session_token] = { value: session_record.id, httponly: true, same_site: :lax }
    Current.session = session_record
  rescue => e
    Rails.logger.error "Auto-login failed: #{e.message}"
    nil
  end

  # Restore validator execution context for the current request.
  #
  # Priority:
  # 1. Cookie validator_session_id (set by ValidatorSessionBinder via URL param)
  #    → supports multi-tab parallel validation (each tab has its own cookie)
  # 2. Latest active ValidatorExecution for the current user (single-session fallback)
  #
  # Sets app.data_version in PostgreSQL so DataVersionable scopes filter correctly.
  # Must run on every request because the connection pool recycles connections.
  def restore_validator_context
    return unless user_signed_in?

    begin
      execution = nil

      cookie_session_id = cookies['validator_session_id']
      if cookie_session_id.present?
        execution = ValidatorExecution.find_by(execution_id: cookie_session_id, user_id: current_user.id)

        unless execution
          Rails.logger.warn "[Validator Context] Cookie session not found: #{cookie_session_id}, clearing"
          cookies.delete('validator_session_id')
        end
      end

      execution ||= ValidatorExecution.active_for_user(current_user.id).first
      return unless execution

      @current_validator_execution = execution

      data_version = execution.data_version
      return unless data_version

      ActiveRecord::Base.connection.execute("SET app.data_version = '#{data_version}'")
      Rails.logger.debug "[Validator Context] data_version=#{data_version} (execution #{execution.execution_id})"
    rescue StandardError => e
      Rails.logger.error "[Validator Context] Failed to restore: #{e.message}"
    end
  end

  def current_validator_execution
    @current_validator_execution
  end

  def find_session_record
    # Try cookie-based authentication first
    if cookies.signed[:session_token].present?
      return Session.find_by_id(cookies.signed[:session_token])
    end

    # Try Authorization header authentication
    if request.headers['Authorization'].present?
      token = request.headers['Authorization'].gsub(/Bearer +/, '')
      return Session.find_by_id(token)
    end

    nil
  end

  def check_session_cookie_availability
    # Check if session cookie is available (privacy + iframe mode detection)
    if request.session.id.nil? || !cookies.key?('_clacky_app_session')
      @privacy_iframe_mode = true
      flash.now[:alert] = "Your browser may be in privacy + iframe mode. " \
                          "Login features may not work properly. " \
                          "Please open in a new window using the top-right button."
    else
      @privacy_iframe_mode = false
    end
  end

  def handle_password_errors(user)
    error_messages = []

    user.errors.each do |error|
      case error.attribute
      when :current_password
        error_messages << "Current password is incorrect"
      when :password
        if error.type == :too_short
          error_messages << "New password must be at least #{User::MIN_PASSWORD} characters long"
        elsif error.type == :invalid
          error_messages << "Password format is invalid"
        else
          error_messages << "New password: #{error.message}"
        end
      when :password_confirmation
        error_messages << "Password confirmation doesn't match"
      when :password_digest
        error_messages << "Password format is invalid"
      end
    end

    if error_messages.empty?
      error_messages = user.errors.full_messages
    end

    return error_messages.first
  end

  # Authentication private methods end
end

